#!/bin/bash

VERSION="0.2.3"
URL="https://waddleforever.com/"
CLIENT="client"
SERVER="server"
STATIC="static"
SPECIAL="special"
FURNITURE="furniture"
MUSIC="music"
NEWSPAPERS="newspapers"
VERSIONS="versions"
CLIENT_URL="$URL$CLIENT-$VERSION-linux.zip"
SERVER_URL="$URL$SERVER-$VERSION-linux.zip"
STATIC_URL="$URL$STATIC-$VERSION.zip"
SPECIAL_URL="$URL$SPECIAL-$VERSION.zip"
FURNITURE_URL="$URL$FURNITURE-$VERSION.zip"
MUSIC_URL="$URL$MUSIC-$VERSION.zip"
NEWSPAPERS_URL="$URL$NEWSPAPERS-$VERSION.zip"
VERSIONS_URL="$URL$VERSIONS-$VERSION.zip"
DEST_FOLDER="."
CLIENT_ZIP="client.zip"
SERVER_ZIP="server.zip"
STATIC_ZIP="static.zip"
SPECIAL_ZIP="special.zip"
FURNITURE_ZIP="furniture.zip"
MUSIC_ZIP="music.zip"
NEWSPAPERS_ZIP="newspapers.zip"
VERSIONS_ZIP="versions.zip"

curl -o "$CLIENT_ZIP" "$CLIENT_URL"
curl -o "$SERVER_ZIP" "$SERVER_URL"
curl -o "$STATIC_ZIP" "$STATIC_URL"
curl -o "$SPECIAL_ZIP" "$SPECIAL_URL"
curl -o "$FURNITURE_ZIP" "$FURNITURE_URL"
curl -o "$MUSIC_ZIP" "$MUSIC_URL"
curl -o "$NEWSPAPERS_ZIP" "$NEWSPAPERS_URL"
curl -o "$VERSIONS_ZIP" "$VERSIONS_URL"

unzip "$CLIENT_ZIP" -d "."
unzip "$SERVER_ZIP" -d "."

mkdir -p "media"
mkdir -p "media/static"
mkdir -p "media/special"
mkdir -p "media/furniture"
mkdir -p "media/music"
mkdir -p "media/newspapers"
mkdir -p "media/versions"
unzip "$STATIC_ZIP" -d "media/static"
unzip "$SPECIAL_ZIP" -d "media/special"
unzip "$FURNITURE_ZIP" -d "media/furniture"
unzip "$MUSIC_ZIP" -d "media/music"
unzip "$NEWSPAPERS_ZIP" -d "media/newspapers"
unzip "$VERSIONS_ZIP" -d "media/versions"

rm "$CLIENT_ZIP"
rm "$SERVER_ZIP"
rm "$STATIC_ZIP"
rm "$SPECIAL_ZIP"
rm "$FURNITURE_ZIP"
rm "$MUSIC_ZIP"
rm "$NEWSPAPERS_ZIP"
rm "$VERSIONS_ZIP"

echo "{}" > "settings.json"

echo "Installation finished! Please check details in https://waddleforever.com/linux on how to run the game."
